[[colors.indexed_colors]]
color = "0xf4a261"
index = 16

[[colors.indexed_colors]]
color = "0xd67ad2"
index = 17

[colors.bright]
black = "0x575860"
blue = "0x86abdc"
cyan = "0x7ad5d6"
green = "0x8ebaa4"
magenta = "0xbaa1e2"
red = "0xd16983"
white = "0xe4e4e5"
yellow = "0xe0c989"

[colors.normal]
black = "0x393b44"
blue = "0x719cd6"
cyan = "0x63cdcf"
green = "0x81b29a"
magenta = "0x9d79d6"
red = "0xc94f6d"
white = "0xdfdfe0"
yellow = "0xdbc074"

[colors.primary]
background = "0x192330"
foreground = "0xcdcecf"

[font.bold]
family = "JetBrainsMono Nerd Font Mono"
# family = "FantasqueSansM Nerd Font Mono"
# style = "Bold"
# family = "Comic Code"
style = "ExtraLight"

[font.bold_italic]
family = "JetBrainsMono Nerd Font Mono"
# family = "FantasqueSansM Nerd Font Mono"
# family = "Comic Code"
style = "Light Italic"

[font.italic]
family = "JetBrainsMono Nerd Font Mono"
# family = "FantasqueSansM Nerd Font Mono"
# family = "Comic Code"
style = "Italic"

[font.normal]
family = "JetBrainsMono Nerd Font Mono"
# family = "FantasqueSansM Nerd Font Mono"
# family = "Comic Code"
style = "ExtraLight"

[font]
size = 16
# size = 15
# size = 14
# size = 12.5

[font.offset]
x = -2
y = 4
# x = -2
# y = 0

[font.glyph_offset]
x = 0
y = 0

# [shell]
# program = "/opt/homebrew/bin/tmux"

[window]
dynamic_padding = true
